# This file is to configure and install nginx in web agent
---
# which host do we need to install nginx in
- hosts: app
  gather_facts: true

# what facts do we want to see while installing

# do we need admin access? yes
  become: true

# what task do we want to perform in this yml file
  tasks:
  - name: update and upgrade
    shell: |
      sudo apt-get update -y
      sudo apt-get upgrade -y
      
  - name: Install Nginx in web Agent Node
    apt: pkg=nginx state=present
    become_user: root

  - name: Setting reverse proxy
    shell: |
      git clone https://github.com/Delwar35/awsFileTransfer
      sudo rm -rf /etc/nginx/sites-available/default
      cp ./awsFileTransfer/default /etc/nginx/sites-available/default
    become_user: root

  - name: Restart Ngnix
    shell: |
      sudo systemctl restart nginx
    become_user: root
